# Generated by Django 3.2.8 on 2021-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211115_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='descrtiption',
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
