# Generated by Django 3.2.8 on 2021-11-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211115_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
